# Generated by Django 5.1.4 on 2024-12-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_default_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_currency',
        ),
    ]
